# Generated by Django 2.2.3 on 2020-01-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20200131_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=128),
        ),
    ]
